In [25]:
import numpy
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.utils import np_utils

seed = 7
numpy.random.seed(seed)

'''
Bibliografy
Open a CSV
https://code.tutsplus.com/es/tutorials/how-to-read-and-write-csv-files-in-python--cms-29907
Save in a dataframe pandas
https://realpython.com/pandas-python-explore-dataset/
Aleatory values for a list 
ttps://www.iteramos.com/pregunta/17907/la-mejor-manera-de-aleatorizar-una-lista-de-cuerdas-en-python

excel
https://gonzalezgouveia.com/como-exportar-data-frames-de-pandas-a-csv-o-excel-en-python/
https://www.delftstack.com/es/howto/python-pandas/pandas-remove-index/#:~:text=Si%20queremos%20eliminar%20la%20columna,en%20el%20m%C3%A9todo%20reset_index()%20
dataframe  
https://www.codigopiton.com/como-crear-un-dataframe-con-pandas-y-python/
'''

'\nBibliografy\nOpen a CSV\nhttps://code.tutsplus.com/es/tutorials/how-to-read-and-write-csv-files-in-python--cms-29907\nSave in a dataframe pandas\nhttps://realpython.com/pandas-python-explore-dataset/\nAleatory values for a list \nttps://www.iteramos.com/pregunta/17907/la-mejor-manera-de-aleatorizar-una-lista-de-cuerdas-en-python\n\nexcel\nhttps://gonzalezgouveia.com/como-exportar-data-frames-de-pandas-a-csv-o-excel-en-python/\nhttps://www.delftstack.com/es/howto/python-pandas/pandas-remove-index/#:~:text=Si%20queremos%20eliminar%20la%20columna,en%20el%20m%C3%A9todo%20reset_index()%20\ndataframe  \nhttps://www.codigopiton.com/como-crear-un-dataframe-con-pandas-y-python/\n'

In [26]:
import csv 

In [27]:
with open('assignment_ds.csv',newline='') as File:
    reader = csv.reader(File)
    for row in reader:
        print(row)

['Temperature', 'L', 'R', 'A_M', 'Color', 'Spectral_Class', 'Type']
['3453', '0.000621', '0.0773', '17.08', 'Red', 'M', '0']
['12098', '689', '7.01', '0.02', 'Blue-white', 'A', '3']
['2731', '0.000437', '0.0856', '18.09', 'Red', 'M', '0']
['37800', '202900', '6.86', '-4.56', 'Blue', 'O', '3']
['8570', '0.00081', '0.0097', '14.2', 'Blue white', 'A', '2']
['3605', '126000', '1124', '-10.81', 'Red', 'M', '5']
['8052', '8.7', '1.8', '2.42', 'Whitish', 'A', '3']
['3574', '200000', '89', '-5.24', 'Red', 'M', '4']
['8829', '537493', '1423', '-10.73', 'White', 'A', '5']
['3625', '74000', '876', '-10.25', 'Red', 'M', '5']
['17383', '342900', '30', '-6.09', 'Blue', 'O', '4']
['3419', '0.000245', '0.126', '17.56', 'Red', 'M', '0']
['3752', '209000', '955', '-11.24', 'Red', 'M', '5']
['9383', '342940', '98', '-6.98', 'Blue', 'O', '4']
['3142', '0.00132', '0.258', '14.12', 'Red', 'M', '1']
['17200', '0.00098', '0.015', '12.45', 'Blue White', 'B', '2']
['3091', '0.0081', '0.24', '11.43', 'Red', 'M',

In [28]:
import pandas as pd
import random

In [29]:
stars = pd.read_csv("assignment_ds.csv")


In [30]:
stars

Temperature              L         R    A_M       Color Spectral_Class  \
0           3453       0.000621   0.07730  17.08         Red              M   
1          12098     689.000000   7.01000   0.02  Blue-white              A   
2           2731       0.000437   0.08560  18.09         Red              M   
3          37800  202900.000000   6.86000  -4.56        Blue              O   
4           8570       0.000810   0.00970  14.20  Blue white              A   
..           ...            ...       ...    ...         ...            ...   
195        13420       0.000590   0.00981  13.67  Blue White              B   
196        19860       0.001100   0.01310  11.34        Blue              B   
197        13023     998.000000   6.21000  -1.38  Blue-white              A   
198        39000  204000.000000  10.60000  -4.70        Blue              O   
199        12010       0.000780   0.00920  12.13  Blue White              B   

     Type  
0       0  
1       3  
2       0  
3       3  
4       2  
..    ...  
195     2  
196     2  
197     3  
198     3  
199     2  

[200 rows x 7 columns]

In [31]:
def rand_index(limit):
    number = 0
    index_list = list(range(limit))
    random.shuffle(index_list)
    return index_list
def select_variables(stars,index_list,number_train):
    #0:6
    #stars.iloc[filas: indices[0->number_rows_for_train] , columnas ]
    x_train = stars.iloc[index_list[0:number_train],0:4]
    x_test = stars.iloc[index_list[number_train:],0:4]
    y_train = stars.iloc[index_list[:number_train], -1]
    y_test =  stars.iloc[index_list[number_train:], -1]
    return x_train, y_train, x_test, y_test

In [32]:
index_list = rand_index(stars.shape[0])

x_train, y_train, x_test, y_test = select_variables(stars,index_list, 160)
x_test

Temperature              L           R     A_M
185         8945      38.000000     2.48700   0.120
59          3575  123000.000000    45.00000  -6.780
197        13023     998.000000     6.21000  -1.380
69          2600       0.000400     0.09600  17.400
34         15680       0.001220     0.01140  11.920
154         9675       0.000450     0.01090  13.980
87          3200  195000.000000    17.00000  -7.220
160         5800       0.810000     0.90000   5.050
118        13340       0.001090     0.01160  12.900
23          2835       0.000340     0.09180  16.960
132         3750  283000.000000  1260.00000  -7.630
41         25070   14500.000000     5.92000  -3.980
86         33421  352000.000000    67.00000  -5.790
133         2650       0.000600     0.14000  11.782
127         3625  184000.000000    84.00000  -6.740
14          3142       0.001320     0.25800  14.120
131         7723       0.000140     0.00878  14.810
170        22012    6748.000000     6.64000  -2.550
18         32460  173800.000000     6.23700  -4.360
175        38234  272830.000000  1356.00000  -9.290
107         5936       1.357000     1.10600   4.460
68         14982       0.001180     0.01130  12.230
92          3463       0.002700     0.67500  14.776
137        24145  382993.000000  1494.00000  -8.840
62         13089     788.000000     5.99200  -0.120
33          3257       0.002400     0.46000  10.730
70         37882  294903.000000  1783.00000  -7.800
125         3095       0.000190     0.49200  10.870
96          3484       0.000551     0.09980  16.670
76         18340       0.001340     0.01240  11.220
145         2994       0.007200     0.28000  13.450
138         7230       0.000080     0.01300  14.080
105         9373  424520.000000    24.00000  -5.990
42         25390  223000.000000    57.00000  -5.920
27         18290       0.001300     0.00934  12.780
49         12912       0.000710     0.00945  12.830
103         2817       0.000980     0.09110  16.450
199        12010       0.000780     0.00920  12.130
10         17383  342900.000000    30.00000  -6.090
115        27739  849420.000000  1252.00000  -7.590

In [33]:
model = Sequential()
model.add(Dense(10, input_dim=4, activation='selu'))
model.add(Dense(6, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


#model.add(Dense(num_pixels, input_dim=num_pixels, kernel_initializer='normal',activation='relu'))
#model.add(Dense(num_classes, kernel_initializer='normal', activation='softmax'))
#model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [34]:
y = []
ls = []
'''
[0,1,2,3,4,5]
[
[1,0,0,0,0,0]
[0,1,0,0,0,0]
[0,0,1,0,0,0]
[0,0,0,1,0,0]
[0,0,0,0,1,0]
[0,0,0,0,0,1]
]
'''
for i in y_train:
    ls = [0 for i in range(6)]
    ls[i] = 1
    y.append(ls)
y = pd.DataFrame(y)

In [35]:
model.fit(x_train, y, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 1s 2ms/step - loss: 59513.3516 - accuracy: 0.2000
Epoch 2/1000
5/5 [==============================] - 0s 1ms/step - loss: 56183.6367 - accuracy: 0.2000
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 52891.0938 - accuracy: 0.2000
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 49683.2773 - accuracy: 0.1187
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 46328.6992 - accuracy: 0.1063
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 43150.6953 - accuracy: 0.1063
Epoch 7/1000
5/5 [==============================] - 0s 2ms/step - loss: 40064.4883 - accuracy: 0.2188
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 37100.9688 - accuracy: 0.1937
Epoch 9/1000
5/5 [==============================] - 0s 3ms/step - loss: 33777.2930 - accuracy: 0.1063
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 30951.318

Epoch 82/1000
5/5 [==============================] - 0s 2ms/step - loss: 43.5175 - accuracy: 0.5437
Epoch 83/1000
5/5 [==============================] - 0s 2ms/step - loss: 19.2553 - accuracy: 0.5750
Epoch 84/1000
5/5 [==============================] - 0s 2ms/step - loss: 47.5336 - accuracy: 0.6187
Epoch 85/1000
5/5 [==============================] - 0s 1ms/step - loss: 43.3802 - accuracy: 0.6062
Epoch 86/1000
5/5 [==============================] - 0s 2ms/step - loss: 20.3232 - accuracy: 0.6062
Epoch 87/1000
5/5 [==============================] - 0s 2ms/step - loss: 22.8228 - accuracy: 0.5750
Epoch 88/1000
5/5 [==============================] - 0s 2ms/step - loss: 16.4697 - accuracy: 0.6125
Epoch 89/1000
5/5 [==============================] - 0s 1ms/step - loss: 10.3196 - accuracy: 0.6125
Epoch 90/1000
5/5 [==============================] - 0s 2ms/step - loss: 14.3662 - accuracy: 0.6875
Epoch 91/1000
5/5 [==============================] - 0s 2ms/step - loss: 12.4786 - accuracy: 0.5500


5/5 [==============================] - 0s 1ms/step - loss: 4.5332 - accuracy: 0.7563
Epoch 164/1000
5/5 [==============================] - 0s 1ms/step - loss: 4.7590 - accuracy: 0.6875
Epoch 165/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.1972 - accuracy: 0.7250
Epoch 166/1000
5/5 [==============================] - 0s 1ms/step - loss: 9.3896 - accuracy: 0.7812
Epoch 167/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.4378 - accuracy: 0.8062
Epoch 168/1000
5/5 [==============================] - 0s 2ms/step - loss: 10.6769 - accuracy: 0.7500
Epoch 169/1000
5/5 [==============================] - 0s 1ms/step - loss: 4.2485 - accuracy: 0.8000
Epoch 170/1000
5/5 [==============================] - 0s 2ms/step - loss: 11.2620 - accuracy: 0.7625
Epoch 171/1000
5/5 [==============================] - 0s 2ms/step - loss: 9.4706 - accuracy: 0.7437
Epoch 172/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.2241 - accuracy: 0.7812
Epoch 173/100

5/5 [==============================] - 0s 2ms/step - loss: 3.9985 - accuracy: 0.7250
Epoch 245/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.0107 - accuracy: 0.7500
Epoch 246/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.5249 - accuracy: 0.7375
Epoch 247/1000
5/5 [==============================] - 0s 1ms/step - loss: 3.7321 - accuracy: 0.8125
Epoch 248/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.9959 - accuracy: 0.7937
Epoch 249/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.0258 - accuracy: 0.8000
Epoch 250/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.6582 - accuracy: 0.7812
Epoch 251/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.6719 - accuracy: 0.8188
Epoch 252/1000
5/5 [==============================] - 0s 1ms/step - loss: 3.5904 - accuracy: 0.7875
Epoch 253/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.8631 - accuracy: 0.8125
Epoch 254/1000


Epoch 325/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.0511 - accuracy: 0.8687
Epoch 326/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.2264 - accuracy: 0.8500
Epoch 327/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.1550 - accuracy: 0.8750
Epoch 328/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.1798 - accuracy: 0.9125
Epoch 329/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.5818 - accuracy: 0.9312
Epoch 330/1000
5/5 [==============================] - 0s 3ms/step - loss: 3.4791 - accuracy: 0.9125
Epoch 331/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.3587 - accuracy: 0.9062
Epoch 332/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.6169 - accuracy: 0.8875
Epoch 333/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.0067 - accuracy: 0.8062
Epoch 334/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.8334 - accuracy: 0.8375


5/5 [==============================] - 0s 2ms/step - loss: 10.8082 - accuracy: 0.7188
Epoch 406/1000
5/5 [==============================] - 0s 1ms/step - loss: 5.3031 - accuracy: 0.7937
Epoch 407/1000
5/5 [==============================] - 0s 2ms/step - loss: 23.5068 - accuracy: 0.7937
Epoch 408/1000
5/5 [==============================] - 0s 2ms/step - loss: 14.0757 - accuracy: 0.8938
Epoch 409/1000
5/5 [==============================] - 0s 2ms/step - loss: 23.8028 - accuracy: 0.7312
Epoch 410/1000
5/5 [==============================] - 0s 1ms/step - loss: 67.0567 - accuracy: 0.7500
Epoch 411/1000
5/5 [==============================] - 0s 2ms/step - loss: 35.8462 - accuracy: 0.7250
Epoch 412/1000
5/5 [==============================] - 0s 2ms/step - loss: 50.2191 - accuracy: 0.7188
Epoch 413/1000
5/5 [==============================] - 0s 2ms/step - loss: 9.1427 - accuracy: 0.7000
Epoch 414/1000
5/5 [==============================] - 0s 2ms/step - loss: 15.1040 - accuracy: 0.7937
Epoch 4

Epoch 487/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.8718 - accuracy: 0.8750
Epoch 488/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.1306 - accuracy: 0.9125
Epoch 489/1000
5/5 [==============================] - 0s 1ms/step - loss: 2.3126 - accuracy: 0.9500
Epoch 490/1000
5/5 [==============================] - 0s 1ms/step - loss: 7.0431 - accuracy: 0.9250
Epoch 491/1000
5/5 [==============================] - 0s 2ms/step - loss: 7.1039 - accuracy: 0.8562
Epoch 492/1000
5/5 [==============================] - 0s 2ms/step - loss: 31.1954 - accuracy: 0.8313
Epoch 493/1000
5/5 [==============================] - 0s 1ms/step - loss: 6.0514 - accuracy: 0.7937
Epoch 494/1000
5/5 [==============================] - 0s 2ms/step - loss: 21.1841 - accuracy: 0.8750
Epoch 495/1000
5/5 [==============================] - ETA: 0s - loss: 0.1512 - accuracy: 0.93 - 0s 2ms/step - loss: 15.5210 - accuracy: 0.9062
Epoch 496/1000
5/5 [==============================] - 0

5/5 [==============================] - 0s 2ms/step - loss: 2.7978 - accuracy: 0.9187
Epoch 569/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.0031 - accuracy: 0.9187
Epoch 570/1000
5/5 [==============================] - 0s 4ms/step - loss: 3.8852 - accuracy: 0.8875
Epoch 571/1000
5/5 [==============================] - 0s 3ms/step - loss: 3.7020 - accuracy: 0.8313
Epoch 572/1000
5/5 [==============================] - ETA: 0s - loss: 0.3003 - accuracy: 0.84 - 0s 4ms/step - loss: 2.8842 - accuracy: 0.8125
Epoch 573/1000
5/5 [==============================] - 0s 5ms/step - loss: 3.1835 - accuracy: 0.8062
Epoch 574/1000
5/5 [==============================] - 0s 2ms/step - loss: 10.6597 - accuracy: 0.8625
Epoch 575/1000
5/5 [==============================] - 0s 4ms/step - loss: 9.2790 - accuracy: 0.8500
Epoch 576/1000
5/5 [==============================] - 0s 4ms/step - loss: 2.7550 - accuracy: 0.9062
Epoch 577/1000
5/5 [==============================] - 0s 3ms/step - loss

5/5 [==============================] - 0s 3ms/step - loss: 10.1273 - accuracy: 0.8875
Epoch 650/1000
5/5 [==============================] - 0s 4ms/step - loss: 9.5890 - accuracy: 0.8500
Epoch 651/1000
5/5 [==============================] - 0s 2ms/step - loss: 8.7872 - accuracy: 0.8562
Epoch 652/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.3780 - accuracy: 0.9000
Epoch 653/1000
5/5 [==============================] - 0s 1ms/step - loss: 9.3011 - accuracy: 0.9062
Epoch 654/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.1243 - accuracy: 0.8875
Epoch 655/1000
5/5 [==============================] - 0s 1ms/step - loss: 5.1135 - accuracy: 0.8875
Epoch 656/1000
5/5 [==============================] - 0s 1ms/step - loss: 8.5556 - accuracy: 0.9187
Epoch 657/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.2240 - accuracy: 0.8250
Epoch 658/1000
5/5 [==============================] - 0s 2ms/step - loss: 9.5290 - accuracy: 0.8438
Epoch 659/1000

Epoch 731/1000
5/5 [==============================] - 0s 3ms/step - loss: 3.1979 - accuracy: 0.9500
Epoch 732/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.5734 - accuracy: 0.9375
Epoch 733/1000
5/5 [==============================] - 0s 3ms/step - loss: 6.9003 - accuracy: 0.9062
Epoch 734/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.6839 - accuracy: 0.9000
Epoch 735/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.0020 - accuracy: 0.8813
Epoch 736/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.2294 - accuracy: 0.9250
Epoch 737/1000
5/5 [==============================] - 0s 2ms/step - loss: 5.6376 - accuracy: 0.9187
Epoch 738/1000
5/5 [==============================] - 0s 2ms/step - loss: 7.8550 - accuracy: 0.9187
Epoch 739/1000
5/5 [==============================] - 0s 4ms/step - loss: 4.7230 - accuracy: 0.9125
Epoch 740/1000
5/5 [==============================] - 0s 4ms/step - loss: 2.7190 - accuracy: 0.8625


5/5 [==============================] - 0s 2ms/step - loss: 18.3402 - accuracy: 0.7312
Epoch 813/1000
5/5 [==============================] - 0s 2ms/step - loss: 21.8214 - accuracy: 0.6625
Epoch 814/1000
5/5 [==============================] - 0s 3ms/step - loss: 16.8687 - accuracy: 0.6500
Epoch 815/1000
5/5 [==============================] - 0s 2ms/step - loss: 53.3133 - accuracy: 0.6687
Epoch 816/1000
5/5 [==============================] - 0s 2ms/step - loss: 108.9017 - accuracy: 0.6875
Epoch 817/1000
5/5 [==============================] - 0s 2ms/step - loss: 21.4349 - accuracy: 0.6750
Epoch 818/1000
5/5 [==============================] - 0s 2ms/step - loss: 26.6363 - accuracy: 0.6687
Epoch 819/1000
5/5 [==============================] - 0s 2ms/step - loss: 28.9040 - accuracy: 0.7125
Epoch 820/1000
5/5 [==============================] - 0s 2ms/step - loss: 18.4050 - accuracy: 0.7375
Epoch 821/1000
5/5 [==============================] - 0s 2ms/step - loss: 7.6212 - accuracy: 0.8313
Epoch

5/5 [==============================] - 0s 2ms/step - loss: 6.7579 - accuracy: 0.7812
Epoch 894/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.7601 - accuracy: 0.8313
Epoch 895/1000
5/5 [==============================] - 0s 2ms/step - loss: 11.4997 - accuracy: 0.8438
Epoch 896/1000
5/5 [==============================] - 0s 2ms/step - loss: 7.5321 - accuracy: 0.8562
Epoch 897/1000
5/5 [==============================] - 0s 3ms/step - loss: 38.2059 - accuracy: 0.7688
Epoch 898/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.1010 - accuracy: 0.8000
Epoch 899/1000
5/5 [==============================] - 0s 2ms/step - loss: 12.6399 - accuracy: 0.7563
Epoch 900/1000
5/5 [==============================] - 0s 3ms/step - loss: 9.5577 - accuracy: 0.8562
Epoch 901/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.1794 - accuracy: 0.8313
Epoch 902/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.7995 - accuracy: 0.8625
Epoch 903/10

5/5 [==============================] - 0s 2ms/step - loss: 5.3000 - accuracy: 0.9062
Epoch 975/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.6940 - accuracy: 0.8938
Epoch 976/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.0887 - accuracy: 0.8687
Epoch 977/1000
5/5 [==============================] - 0s 1ms/step - loss: 2.7506 - accuracy: 0.9250
Epoch 978/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.7238 - accuracy: 0.9563
Epoch 979/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.4826 - accuracy: 0.9438
Epoch 980/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.9174 - accuracy: 0.9375
Epoch 981/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.7440 - accuracy: 0.9438
Epoch 982/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.9533 - accuracy: 0.9375
Epoch 983/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.9316 - accuracy: 0.9187
Epoch 984/1000


In [124]:
# evaluamos el modelo
scores = model.evaluate(x_train, y)
 
    
y_t = []
ls = []
for i in y_test:
    ls = [0 for i in range(6)]
    ls[i] = 1
    y_t.append(ls)
y_t = pd.DataFrame(y_t)
y_predicted = model.predict(x_test).round()
print (y_predicted)
print (y_t)

5/5 [==============================] - 0s 3ms/step - loss: 0.4508 - accuracy: 0.9563
[[0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]]
    0  1  2  3  4  5
0   0  0  0  0  1  0
1   1  0  0  0  0  0
2   1  0  0

In [125]:
def convert_at_type_array(mat):
    types = []
    for row in mat:
        value = 0
        for index in row:
            if (index >= 1):
                break
            value += 1
        types.append(value)
    return types

def stadistics(y_real, y_predicted):
    counter = 0
    total = len(y_real)
    for i in range(total):
        if (y_real[i] == y_predicted[i]):
            counter += 1
    print(f"Cantidad total de pruebas: {total}")
    print(f"Cantidad total de aciertos: {counter}")
    print(f"Porcentaje de aciertos: {counter/total*100}%")

    
stadistics(convert_at_type_array(y_predicted),convert_at_type_array(y_t.to_numpy()))

print(convert_at_type_array(y_predicted))
print(convert_at_type_array(y_t.to_numpy())) 


Cantidad total de pruebas: 40
Cantidad total de aciertos: 39
Porcentaje de aciertos: 97.5%
[4, 0, 0, 2, 3, 5, 1, 2, 5, 5, 5, 4, 2, 0, 2, 4, 4, 4, 2, 5, 1, 4, 1, 4, 0, 5, 3, 1, 1, 2, 2, 0, 1, 0, 2, 5, 2, 5, 5, 3]
[4, 0, 0, 2, 3, 5, 1, 2, 5, 5, 5, 4, 2, 0, 2, 4, 4, 4, 2, 5, 1, 4, 1, 4, 0, 5, 3, 1, 3, 2, 2, 0, 1, 0, 2, 5, 2, 5, 5, 3]


In [134]:
name = "nombre_11_10_21"

In [131]:
# serializar el modelo a JSON
model_json = model.to_json()
with open("./jsons/"+name+".json", "w") as json_file:
    json_file.write(model_json)
# serializar los pesos a HDF5
model.save_weights("./h_fives/"+name+".h5")
print("Modelo Guardado!")

Modelo Guardado!


In [84]:
#ver
#https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/

In [137]:
from keras.models import model_from_json
json_file = open("./jsons/"+name+'.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# cargar pesos al nuevo modelo
loaded_model.load_weights("./h_fives/"+name+".h5")
print("Cargado modelo desde disco.")
 
# Compilar modelo cargado y listo para usar.
loaded_model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

y_predicted_exp = loaded_model.predict(x_test).round()

Cargado modelo desde disco.


In [138]:
stadistics(convert_at_type_array(y_predicted_exp),convert_at_type_array(y_t.to_numpy()))

print(convert_at_type_array(y_predicted_exp))
print(convert_at_type_array(y_t.to_numpy())) 

Cantidad total de pruebas: 40
Cantidad total de aciertos: 39
Porcentaje de aciertos: 97.5%
[4, 0, 0, 2, 3, 5, 1, 2, 5, 5, 5, 4, 2, 0, 2, 4, 4, 4, 2, 5, 1, 4, 1, 4, 0, 5, 3, 1, 1, 2, 2, 0, 1, 0, 2, 5, 2, 5, 5, 3]
[4, 0, 0, 2, 3, 5, 1, 2, 5, 5, 5, 4, 2, 0, 2, 4, 4, 4, 2, 5, 1, 4, 1, 4, 0, 5, 3, 1, 3, 2, 2, 0, 1, 0, 2, 5, 2, 5, 5, 3]


In [139]:
stars_comp = pd.read_csv("test_ds.csv")
stars_comp

Temperature             L           R     A_M       Color Spectral_Class
0         21020       0.00150     0.01120  11.520        Blue              B
1          2935       0.00087     0.09320  16.880         Red              M
2         16390    1278.00000     5.68000  -3.320  Blue-white              B
3          3628       0.00550     0.39300  10.480         Red              M
4          3496       0.00125     0.33600  14.940         Red              M
5          3342       0.00150     0.30700  11.870         Red              M
6         17140     883.00000     5.65300  -2.640  Blue-white              B
7         24490  248490.00000  1134.50000  -8.240  Blue-white              B
8         11000  170000.00000  1779.00000  -9.900  Blue-white              B
9         24020       0.00159     0.01270  10.550        Blue              B
10        23678  244290.00000    35.00000  -6.270        Blue              O
11        16790       0.00140     0.01210  12.870        Blue              B
12         9700      74.00000     2.89000   0.160     Whitish              B
13         2983       0.00024     0.09400  16.090         Red              M
14         3218       0.00054     0.11000  20.020         Red              M
15        12893  184000.00000    36.00000  -6.340        Blue              O
16        13720       0.00018     0.00892  12.970       white              F
17         3650  310000.00000  1324.00000  -7.790         Red              M
18         3541       0.00130     0.25600  14.330         Red              M
19        33300  240000.00000    12.00000  -6.500        Blue              B
20         2799       0.00180     0.16000  14.790         Red              M
21         3553  145000.00000  1324.00000 -11.030         Red              M
22         8927  239000.00000    35.00000  -7.340        Blue              O
23         3826  200000.00000    19.00000  -6.930         Red              M
24         3068       0.00240     0.17000  16.120         Red              M
25         3150       0.00880     0.35000  11.940         Red              M
26         2650       0.00069     0.11000  17.450         Red              M
27        21904  748490.00000  1130.00000  -7.670  Blue-white              B
28        20120    4720.00000     6.78000  -3.400  Blue-white              B
29        12749  332520.00000    76.00000  -7.020        Blue              O
30        19400   10920.00000     6.03000  -3.080  Blue-white              B
31        26140   14520.00000     5.49000  -3.800  Blue-white              B
32         3146       0.00015     0.09320  16.920         Red              M
33         3399  117000.00000  1486.00000 -10.920         Red              M
34         2935       0.00014     0.11600  18.890         Red              M
35         3340       0.00380     0.24000  13.070         Red              M
36        23095  347820.00000    86.00000  -5.905        Blue              O
37         3225       0.00076     0.12100  19.630         Red              M
38         2700       0.00018     0.13000  16.050         Red              M

In [141]:
def select_variables_x_test(stars):
    x_test = stars.iloc[:,0:4]
    return x_test
stars_comp = select_variables_x_test(stars_comp)

In [145]:
y_predicted_comp = loaded_model.predict(stars_comp).round()
y_predicted_comp = convert_at_type_array(y_predicted_comp)

print(y_predicted_comp)

[2, 0, 3, 1, 1, 1, 3, 5, 5, 2, 4, 2, 3, 0, 0, 4, 2, 5, 1, 4, 0, 5, 4, 4, 0, 1, 0, 5, 3, 4, 3, 3, 0, 5, 0, 1, 4, 0, 0]


In [151]:
indexs = range(1,len(y_predicted_comp)+1)

In [166]:
solution = pd.DataFrame()
solution["Id"] = indexs
solution["Type"] = y_predicted_comp
solution.set_index("Id")

Type
Id      
1      2
2      0
3      3
4      1
5      1
6      1
7      3
8      5
9      5
10     2
11     4
12     2
13     3
14     0
15     0
16     4
17     2
18     5
19     1
20     4
21     0
22     5
23     4
24     4
25     0
26     1
27     0
28     5
29     3
30     4
31     3
32     3
33     0
34     5
35     0
36     1
37     4
38     0
39     0

In [167]:
#submission.csv
solution.set_index("Id").to_csv("submission.csv",encoding="utf-8")