In [215]:
import numpy
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.utils import np_utils

seed = 7
numpy.random.seed(seed)

'''
Bibliografy
Open a CSV
https://code.tutsplus.com/es/tutorials/how-to-read-and-write-csv-files-in-python--cms-29907
Save in a dataframe pandas
https://realpython.com/pandas-python-explore-dataset/
Aleatory values for a list 
ttps://www.iteramos.com/pregunta/17907/la-mejor-manera-de-aleatorizar-una-lista-de-cuerdas-en-python

'''

'\nBibliografy\nOpen a CSV\nhttps://code.tutsplus.com/es/tutorials/how-to-read-and-write-csv-files-in-python--cms-29907\nSave in a dataframe pandas\nhttps://realpython.com/pandas-python-explore-dataset/\nAleatory values for a list \nttps://www.iteramos.com/pregunta/17907/la-mejor-manera-de-aleatorizar-una-lista-de-cuerdas-en-python\n\n'

In [216]:
import csv 

In [217]:
with open('assignment_ds.csv',newline='') as File:
    reader = csv.reader(File)
    for row in reader:
        print(row)

['Temperature', 'L', 'R', 'A_M', 'Color', 'Spectral_Class', 'Type']
['3453', '0.000621', '0.0773', '17.08', 'Red', 'M', '0']
['12098', '689', '7.01', '0.02', 'Blue-white', 'A', '3']
['2731', '0.000437', '0.0856', '18.09', 'Red', 'M', '0']
['37800', '202900', '6.86', '-4.56', 'Blue', 'O', '3']
['8570', '0.00081', '0.0097', '14.2', 'Blue white', 'A', '2']
['3605', '126000', '1124', '-10.81', 'Red', 'M', '5']
['8052', '8.7', '1.8', '2.42', 'Whitish', 'A', '3']
['3574', '200000', '89', '-5.24', 'Red', 'M', '4']
['8829', '537493', '1423', '-10.73', 'White', 'A', '5']
['3625', '74000', '876', '-10.25', 'Red', 'M', '5']
['17383', '342900', '30', '-6.09', 'Blue', 'O', '4']
['3419', '0.000245', '0.126', '17.56', 'Red', 'M', '0']
['3752', '209000', '955', '-11.24', 'Red', 'M', '5']
['9383', '342940', '98', '-6.98', 'Blue', 'O', '4']
['3142', '0.00132', '0.258', '14.12', 'Red', 'M', '1']
['17200', '0.00098', '0.015', '12.45', 'Blue White', 'B', '2']
['3091', '0.0081', '0.24', '11.43', 'Red', 'M',

In [218]:
import pandas as pd
import random

In [219]:
stars = pd.read_csv("assignment_ds.csv")


In [220]:
stars

Temperature              L         R    A_M       Color Spectral_Class  \
0           3453       0.000621   0.07730  17.08         Red              M   
1          12098     689.000000   7.01000   0.02  Blue-white              A   
2           2731       0.000437   0.08560  18.09         Red              M   
3          37800  202900.000000   6.86000  -4.56        Blue              O   
4           8570       0.000810   0.00970  14.20  Blue white              A   
..           ...            ...       ...    ...         ...            ...   
195        13420       0.000590   0.00981  13.67  Blue White              B   
196        19860       0.001100   0.01310  11.34        Blue              B   
197        13023     998.000000   6.21000  -1.38  Blue-white              A   
198        39000  204000.000000  10.60000  -4.70        Blue              O   
199        12010       0.000780   0.00920  12.13  Blue White              B   

     Type  
0       0  
1       3  
2       0  
3       3  
4       2  
..    ...  
195     2  
196     2  
197     3  
198     3  
199     2  

[200 rows x 7 columns]

In [221]:
def rand_index(limit):
    number = 0
    index_list = list(range(limit))
    random.shuffle(index_list)
    return index_list
def select_variables(stars,index_list,number_train):
    #0:6
    x_train = stars.iloc[index_list[:number_train],0:4]
    x_test = stars.iloc[index_list[number_train:],0:4]
    y_train = stars.iloc[index_list[:number_train], -1]
    y_test =  stars.iloc[index_list[number_train:], -1]
    return x_train, y_train, x_test, y_test

In [222]:
index_list = rand_index(stars.shape[0])

x_train, y_train, x_test, y_test = select_variables(stars,index_list, 190)
x_test

Temperature             L          R     A_M
130         3692       0.00367     0.4700  10.800
44         25000       0.05600     0.0084  10.580
117         3610  132000.00000  1522.0000 -10.860
147        11567  251000.00000    36.0000  -6.245
146         3270  150000.00000    88.0000  -6.020
69          2600       0.00040     0.0960  17.400
29          2871       0.00072     0.1200  19.430
59          3575  123000.00000    45.0000  -6.780
170        22012    6748.00000     6.6400  -2.550
175        38234  272830.00000  1356.0000  -9.290

In [223]:
model = Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(6, activation='softmax'))

#model.add(Dense(num_pixels, input_dim=num_pixels, kernel_initializer='normal',activation='relu'))
#model.add(Dense(num_classes, kernel_initializer='normal', activation='softmax'))
#model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [224]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [225]:
y = []
ls = []
for i in y_train:
    ls = [0 for i in range(6)]
    ls[i] = 1
    y.append(ls)
y = pd.DataFrame(y)

In [227]:
model.fit(x_train, y, epochs=1000)

Epoch 1/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.3843 - accuracy: 0.7421
Epoch 2/1000
6/6 [==============================] - 0s 4ms/step - loss: 3.8816 - accuracy: 0.6895
Epoch 3/1000
6/6 [==============================] - 0s 4ms/step - loss: 3.5183 - accuracy: 0.7421
Epoch 4/1000
6/6 [==============================] - 0s 2ms/step - loss: 3.5902 - accuracy: 0.7632
Epoch 5/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.7049 - accuracy: 0.8053
Epoch 6/1000
6/6 [==============================] - 0s 5ms/step - loss: 3.8736 - accuracy: 0.8053
Epoch 7/1000
6/6 [==============================] - 0s 3ms/step - loss: 5.3075 - accuracy: 0.6263
Epoch 8/1000
6/6 [==============================] - ETA: 0s - loss: 9.1517 - accuracy: 0.50 - 0s 3ms/step - loss: 5.1068 - accuracy: 0.5737
Epoch 9/1000
6/6 [==============================] - 0s 5ms/step - loss: 5.0101 - accuracy: 0.5895
Epoch 10/1000
6/6 [==============================] - 0s 4ms/step - loss: 7.9

6/6 [==============================] - 0s 3ms/step - loss: 9.4293 - accuracy: 0.7632
Epoch 83/1000
6/6 [==============================] - ETA: 0s - loss: 0.3374 - accuracy: 0.90 - 0s 3ms/step - loss: 5.4224 - accuracy: 0.8158
Epoch 84/1000
6/6 [==============================] - 0s 3ms/step - loss: 9.7104 - accuracy: 0.8053
Epoch 85/1000
6/6 [==============================] - 0s 3ms/step - loss: 9.3415 - accuracy: 0.7737
Epoch 86/1000
6/6 [==============================] - 0s 3ms/step - loss: 6.0988 - accuracy: 0.8526
Epoch 87/1000
6/6 [==============================] - 0s 3ms/step - loss: 5.9205 - accuracy: 0.7842
Epoch 88/1000
6/6 [==============================] - 0s 5ms/step - loss: 6.1353 - accuracy: 0.8158
Epoch 89/1000
6/6 [==============================] - 0s 4ms/step - loss: 3.9316 - accuracy: 0.7947
Epoch 90/1000
6/6 [==============================] - 0s 4ms/step - loss: 3.5191 - accuracy: 0.7737
Epoch 91/1000
6/6 [==============================] - 0s 8ms/step - loss: 3.6443 -

6/6 [==============================] - 0s 4ms/step - loss: 3.8793 - accuracy: 0.7895
Epoch 164/1000
6/6 [==============================] - 0s 4ms/step - loss: 4.1749 - accuracy: 0.7579
Epoch 165/1000
6/6 [==============================] - 0s 3ms/step - loss: 5.0770 - accuracy: 0.8000
Epoch 166/1000
6/6 [==============================] - ETA: 0s - loss: 0.2231 - accuracy: 0.87 - 0s 3ms/step - loss: 4.4974 - accuracy: 0.8211
Epoch 167/1000
6/6 [==============================] - 0s 3ms/step - loss: 5.7636 - accuracy: 0.8263
Epoch 168/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.1373 - accuracy: 0.8526
Epoch 169/1000
6/6 [==============================] - 0s 3ms/step - loss: 2.8236 - accuracy: 0.8000
Epoch 170/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.5272 - accuracy: 0.8263
Epoch 171/1000
6/6 [==============================] - 0s 2ms/step - loss: 3.6521 - accuracy: 0.9000
Epoch 172/1000
6/6 [==============================] - 0s 2ms/step - loss:

6/6 [==============================] - 0s 2ms/step - loss: 4.9504 - accuracy: 0.8158
Epoch 244/1000
6/6 [==============================] - 0s 4ms/step - loss: 4.0518 - accuracy: 0.8000
Epoch 245/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.3968 - accuracy: 0.7947
Epoch 246/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.6036 - accuracy: 0.7737
Epoch 247/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.6881 - accuracy: 0.7684
Epoch 248/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.9428 - accuracy: 0.8000
Epoch 249/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.7790 - accuracy: 0.8158
Epoch 250/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.7004 - accuracy: 0.7579
Epoch 251/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.2070 - accuracy: 0.8000
Epoch 252/1000
6/6 [==============================] - 0s 2ms/step - loss: 5.3999 - accuracy: 0.8263
Epoch 253/1000


6/6 [==============================] - 0s 2ms/step - loss: 11.2001 - accuracy: 0.7789
Epoch 325/1000
6/6 [==============================] - 0s 3ms/step - loss: 9.1982 - accuracy: 0.7368
Epoch 326/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.4405 - accuracy: 0.8105
Epoch 327/1000
6/6 [==============================] - 0s 3ms/step - loss: 6.4727 - accuracy: 0.8158
Epoch 328/1000
6/6 [==============================] - 0s 2ms/step - loss: 3.6911 - accuracy: 0.8158
Epoch 329/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.8684 - accuracy: 0.7895
Epoch 330/1000
6/6 [==============================] - ETA: 0s - loss: 6.2148 - accuracy: 0.87 - 0s 2ms/step - loss: 4.0650 - accuracy: 0.8158
Epoch 331/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.6522 - accuracy: 0.7842
Epoch 332/1000
6/6 [==============================] - 0s 3ms/step - loss: 7.0639 - accuracy: 0.8158
Epoch 333/1000
6/6 [==============================] - 0s 2ms/step - loss

6/6 [==============================] - 0s 3ms/step - loss: 3.9855 - accuracy: 0.8368
Epoch 406/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.6450 - accuracy: 0.8526
Epoch 407/1000
6/6 [==============================] - 0s 3ms/step - loss: 5.7434 - accuracy: 0.8105
Epoch 408/1000
6/6 [==============================] - 0s 3ms/step - loss: 2.2804 - accuracy: 0.7684
Epoch 409/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.1953 - accuracy: 0.8632
Epoch 410/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.3830 - accuracy: 0.7842
Epoch 411/1000
6/6 [==============================] - 0s 3ms/step - loss: 5.4857 - accuracy: 0.8211
Epoch 412/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.1019 - accuracy: 0.8526
Epoch 413/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.9388 - accuracy: 0.8526
Epoch 414/1000
6/6 [==============================] - 0s 2ms/step - loss: 3.0624 - accuracy: 0.8263
Epoch 415/1000


6/6 [==============================] - 0s 2ms/step - loss: 6.0704 - accuracy: 0.7947
Epoch 487/1000
6/6 [==============================] - 0s 3ms/step - loss: 22.5506 - accuracy: 0.8263
Epoch 488/1000
6/6 [==============================] - 0s 3ms/step - loss: 33.4262 - accuracy: 0.7684
Epoch 489/1000
6/6 [==============================] - 0s 3ms/step - loss: 17.4644 - accuracy: 0.7316
Epoch 490/1000
6/6 [==============================] - 0s 3ms/step - loss: 7.9904 - accuracy: 0.8263
Epoch 491/1000
6/6 [==============================] - 0s 3ms/step - loss: 11.8544 - accuracy: 0.7316
Epoch 492/1000
6/6 [==============================] - 0s 3ms/step - loss: 11.7819 - accuracy: 0.7632
Epoch 493/1000
6/6 [==============================] - 0s 5ms/step - loss: 8.5751 - accuracy: 0.7789
Epoch 494/1000
6/6 [==============================] - 0s 4ms/step - loss: 4.1330 - accuracy: 0.8000
Epoch 495/1000
6/6 [==============================] - 0s 3ms/step - loss: 6.4816 - accuracy: 0.7789
Epoch 496/

6/6 [==============================] - 0s 3ms/step - loss: 3.2973 - accuracy: 0.8684
Epoch 568/1000
6/6 [==============================] - 0s 2ms/step - loss: 3.6532 - accuracy: 0.8737
Epoch 569/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.9892 - accuracy: 0.9158
Epoch 570/1000
6/6 [==============================] - 0s 3ms/step - loss: 2.9581 - accuracy: 0.9105
Epoch 571/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.0548 - accuracy: 0.9316
Epoch 572/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.2135 - accuracy: 0.8947
Epoch 573/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.8989 - accuracy: 0.8105
Epoch 574/1000
6/6 [==============================] - 0s 3ms/step - loss: 5.6136 - accuracy: 0.8316
Epoch 575/1000
6/6 [==============================] - 0s 2ms/step - loss: 3.7225 - accuracy: 0.7895
Epoch 576/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.2286 - accuracy: 0.7947
Epoch 577/1000


6/6 [==============================] - 0s 3ms/step - loss: 7.0284 - accuracy: 0.9053
Epoch 649/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.5621 - accuracy: 0.9158
Epoch 650/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.0321 - accuracy: 0.9368
Epoch 651/1000
6/6 [==============================] - 0s 3ms/step - loss: 8.2856 - accuracy: 0.8895
Epoch 652/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.2380 - accuracy: 0.9000
Epoch 653/1000
6/6 [==============================] - 0s 3ms/step - loss: 2.6458 - accuracy: 0.8526
Epoch 654/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.9084 - accuracy: 0.9000
Epoch 655/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.7044 - accuracy: 0.9105
Epoch 656/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.1761 - accuracy: 0.8684
Epoch 657/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.2078 - accuracy: 0.8632
Epoch 658/1000


6/6 [==============================] - 0s 2ms/step - loss: 35.8093 - accuracy: 0.8526
Epoch 730/1000
6/6 [==============================] - ETA: 0s - loss: 95.1939 - accuracy: 0.656 - 0s 4ms/step - loss: 23.8691 - accuracy: 0.8368
Epoch 731/1000
6/6 [==============================] - 0s 2ms/step - loss: 14.0672 - accuracy: 0.8947
Epoch 732/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.5480 - accuracy: 0.9368
Epoch 733/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.8437 - accuracy: 0.8421
Epoch 734/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.3729 - accuracy: 0.8526
Epoch 735/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.1586 - accuracy: 0.8368
Epoch 736/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.8572 - accuracy: 0.8737
Epoch 737/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.5392 - accuracy: 0.8895
Epoch 738/1000
6/6 [==============================] - 0s 3ms/step - 

6/6 [==============================] - 0s 3ms/step - loss: 2.7818 - accuracy: 0.8368
Epoch 810/1000
6/6 [==============================] - 0s 2ms/step - loss: 3.3736 - accuracy: 0.8737
Epoch 811/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.1607 - accuracy: 0.8632
Epoch 812/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.0659 - accuracy: 0.8368
Epoch 813/1000
6/6 [==============================] - 0s 2ms/step - loss: 3.6268 - accuracy: 0.8895
Epoch 814/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.0922 - accuracy: 0.8263
Epoch 815/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.6476 - accuracy: 0.8789
Epoch 816/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.5437 - accuracy: 0.8316
Epoch 817/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.7700 - accuracy: 0.8263
Epoch 818/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.3829 - accuracy: 0.8947
Epoch 819/1000


6/6 [==============================] - 0s 3ms/step - loss: 46.8657 - accuracy: 0.7684
Epoch 892/1000
6/6 [==============================] - 0s 2ms/step - loss: 29.3464 - accuracy: 0.8211
Epoch 893/1000
6/6 [==============================] - 0s 3ms/step - loss: 7.2723 - accuracy: 0.7789
Epoch 894/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.4504 - accuracy: 0.8526
Epoch 895/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.9626 - accuracy: 0.9053
Epoch 896/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.4304 - accuracy: 0.8895
Epoch 897/1000
6/6 [==============================] - 0s 3ms/step - loss: 2.9451 - accuracy: 0.9368
Epoch 898/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.8205 - accuracy: 0.8421
Epoch 899/1000
6/6 [==============================] - 0s 2ms/step - loss: 4.3999 - accuracy: 0.8737
Epoch 900/1000
6/6 [==============================] - 0s 3ms/step - loss: 3.6247 - accuracy: 0.7789
Epoch 901/100

6/6 [==============================] - 0s 4ms/step - loss: 25.8556 - accuracy: 0.7684
Epoch 973/1000
6/6 [==============================] - 0s 2ms/step - loss: 16.8215 - accuracy: 0.6632
Epoch 974/1000
6/6 [==============================] - 0s 2ms/step - loss: 30.1286 - accuracy: 0.7632
Epoch 975/1000
6/6 [==============================] - 0s 2ms/step - loss: 13.2847 - accuracy: 0.7474
Epoch 976/1000
6/6 [==============================] - 0s 2ms/step - loss: 6.6041 - accuracy: 0.7316
Epoch 977/1000
6/6 [==============================] - 0s 4ms/step - loss: 4.4653 - accuracy: 0.7789
Epoch 978/1000
6/6 [==============================] - 0s 3ms/step - loss: 4.7870 - accuracy: 0.7263
Epoch 979/1000
6/6 [==============================] - 0s 3ms/step - loss: 5.2263 - accuracy: 0.7842
Epoch 980/1000
6/6 [==============================] - 0s 2ms/step - loss: 5.7460 - accuracy: 0.7895
Epoch 981/1000
6/6 [==============================] - 0s 3ms/step - loss: 2.7506 - accuracy: 0.8842
Epoch 982/1

In [229]:
# evaluamos el modelo
scores = model.evaluate(x_train, y)
 
    
y_t = []
ls = []
for i in y_test:
    ls = [0 for i in range(6)]
    ls[i] = 1
    y_t.append(ls)
y_t = pd.DataFrame(y_t)

print (model.predict(x_test).round())
print (y_t)

6/6 [==============================] - 0s 2ms/step - loss: 3.8260 - accuracy: 0.9158
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
   0  1  2  3  4  5
0  0  1  0  0  0  0
1  0  0  1  0  0  0
2  0  0  0  0  0  1
3  0  0  0  0  1  0
4  0  0  0  0  1  0
5  1  0  0  0  0  0
6  1  0  0  0  0  0
7  0  0  0  0  1  0
8  0  0  0  1  0  0
9  0  0  0  0  0  1


In [ ]:
#ver
#https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/